version: "3.9"

services:
  db:
    image: postgres:16
    container_name: realestate-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realestate
    ports:
      - "5432:5432"
    volumes:
      - ./db_test/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    container_name: realestate-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]